name: orka_sports
description: "A new Flutter project."
publish_to: "none"
version: 1.5.4+69

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  country_picker: ^2.0.27
  provider: ^6.1.2
  numberpicker: ^2.1.2
  equatable: ^2.0.7
  http: ^1.2.1
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  phone_numbers_parser: ^8.1.0
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^5.0.2
  image_picker: ^1.0.7
  location: ^6.0.2
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.5.0
  geocoding: ^3.0.0
  geolocator: ^10.1.0
  fl_chart: ^0.69.0
  font_awesome_flutter: ^10.7.0
  get_it: ^7.7.0
  dio: ^5.4.0
  flutter_riverpod: ^2.5.1
  flutter_launcher_icons: ^0.13.1
  readmore: ^2.2.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.5
  syncfusion_flutter_gauges: ^24.2.9
  google_sign_in: ^6.2.1
  firebase_core: ^2.27.0
  dropdown_button2: ^2.3.9
  firebase_messaging: ^14.7.10
  awesome_notifications: ^0.9.3
  flutter_screenutil: ^5.9.0
  sign_in_with_apple: ^5.0.0
  flutter_activity_recognition: ^3.0.0
  pedometer: ^4.0.1
  lottie: ^2.7.0
  google_fonts: ^6.1.0
  camera: ^0.10.5+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Fit_First.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/Lottie/
